name: shared_atlas_dart
description: Generated Dart models for Tainiex Atlas
version: 0.0.25-jq22d
homepage: https://github.com/tainiex/tainiex-atlas
repository: https://github.com/tainiex/tainiex-atlas
issue_tracker: https://github.com/tainiex/tainiex-atlas/issues
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.7.0